name: SonarQube Analysis

on:
  push:
    branches:
      - main

jobs:
  sonarqube:
    name: SonarQube Analysis
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Build with Maven
      run: mvn clean package

    - name: SonarQube Analysis
      uses: SonarSource/sonarqube-scan-action@v1
      with:
        projectBaseDir: .
        projectName: "Springboot-App"
        serverUrl: "http://40.124.177.46:9000"
        token: sqa_9f41ef4119a1c8d49ac5ee19c7a2158d04f480ce
