apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: springboot-ingress
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path:
        backend:
          serviceName: springboot-app
            servicePort: 80
